version: "2.2"
services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      APPID: 658d9d99e91f7f79e9dacaab32d00f4a
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      ENDPOINT: http://ec2-44-203-121-60.compute-1.amazonaws.com:9000/api
